[theme]
primaryColor = "#1f77b4"            # your main brand blue
backgroundColor = "#f8f9fa"         # very light gray
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"               # dark slate gray
font = "sans serif"                 # or "serif", "monospace"
